paths:
  static: public
  uploads: public/uploads
timezone: Europe/Warsaw
markdown:
  engine: commonmark
  options:
    gfm: true
collections_config:
  pages:
    path: ''
    icon: wysiwyg
    disable_url: true
